package:
  name: '{{ PACKAGE_NAME }}'
  version: '{{ PACKAGE_VERSION }}'
source:
  path: ../src
requirements:
  run:
  - dash-table
  - dash
  - lxml
  - pandas
  - polars
  - numpy
  - ipykernel
  - pip
  - foundry-transforms-lib-python
  pip:
  - dashtable
